name: FoxetGSI-builder

on:
  workflow_dispatch:
    inputs:
      rom_type:
        description: 'Type of ROM (e.g., Pixel, Generic)'
        required: true
        default: 'Pixel'
      rom_link:
        description: 'Link to the ROM file'
        required: true
        default: 'https://dl.google.com/dl/android/aosp/barbet-sp1a.210812.015-factory-13f4d9f2.zip'

jobs:
  Build_GSI:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Clone FoxetGSI-tool
        run: |
          git clone --recurse-submodules https://github.com/MaddIsHere/FoxetGSITool.git
      - name: Install dependencies
        run: |
          cd FoxetGSITool
          sudo apt update
          sudo apt install unace unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack arj cabextract rename liblzma-dev python3-pip brotli lz4 protobuf-compiler git gawk aria2 kpartx e2fsprogs qemu-utils android-sdk-libsparse-utils exfatprogs
      - name: Build GSI
        env:
          ROM_TYPE: ${{ github.event.inputs.rom_type }}
          ROM_LINK: ${{ github.event.inputs.rom_link }}
        run: |
          cd FoxetGSITool
            sudo bash LinkToGSI.sh "$ROM_LINK" "$ROM_TYPE"
            ls
      - name: Prepare artifacts directory
        run: |
          mkdir -p $GITHUB_WORKSPACE/artifacts
          sudo chmod -R 777 $GITHUB_WORKSPACE/artifacts
      - name: Process and Package Files
        id: package
        run: |
          cd $GITHUB_WORKSPACE/FoxetGSITool/Output || exit 1
          ls
          if [ $(ls -1 *.img 2>/dev/null | wc -l) -eq 0 ]; then
            echo "::error::No .img files found!"
            exit 1
          fi
          timestamp=$(date +'%d.%m.%y_%H.%M')
          for img_file in *.img; do
            if [ -e "$img_file" ]; then
              base_name="${img_file%.img}"
              
              7z a -mx=5 -mmt=on "$GITHUB_WORKSPACE/artifacts/${base_name}.7z" "$GITHUB_WORKSPACE/FoxetGSITool/Output/${img_file}"
              
              echo "release_name=${base_name}_${timestamp}" >> $GITHUB_OUTPUT
              echo "tag_name=${rom_type}-${timestamp}" >> $GITHUB_OUTPUT
              echo "file_name=${base_name}.7z" >> $GITHUB_OUTPUT
            fi
          done
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.package.outputs.tag_name }}
          name: ${{ steps.package.outputs.release_name }}
          files: |
            ${{ github.workspace }}/artifacts/${{ steps.package.outputs.file_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
